ApplicationDevelopment/demoweb/Models/Brand.cs
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace demoweb.Models
{
    //Brand - Mobile : 1 to Many
    //Brand - Country : Many to 1
    public class Brand
    {
        public int Id { get; set; }

        [Required]
        [StringLength(20, MinimumLength = 3)]
        public string Name { get; set; }
        
        public ICollection<Mobile> Mobiles { get; set; }

        [Required]
        [Display(Name = "Country Name")]
        public int CountryId { get; set; }
        
        public Country Country { get; set; }
    }
}

ApplicationDevelopment/demoweb/Controllers/BrandController.cs
using demoweb.Data;
using demoweb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace demoweb.Controllers
{
    public class BrandController : Controller
    {
        //khai báo ApplicationDbContext để truy xuất và thay đổi dữ liệu của bảng
        private ApplicationDbContext context;
        public BrandController (ApplicationDbContext applicationDbContext)
        {
            context = applicationDbContext;
        }

        //load toàn bộ dữ liệu của bảng  
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(context.Brand.ToList());
        }

        //xoá dữ liệu từ bảng
        
        public IActionResult Delete(int id)
        {
            var brand = context.Brand.Find(id);
            context.Brand.Remove(brand);
            context.SaveChanges();
            TempData["Message"] = "Delete brand successfully !";
            return RedirectToAction("Index");
        }

        //xem thông tin theo id
        public IActionResult Detail (int id)
        {
            var brand = context.Brand.Include(b => b.Mobiles)  //Brand - Mobile : 1 - M
                                     .Include(b => b.Country)  //Brand - Country : M - 1
                                     .FirstOrDefault(b => b.Id == id);
            return View(brand);
        }

        //thêm dữ liệu vào bảng
        //hàm 1: render ra view
        [HttpGet]
        public IActionResult Create()
        {
            //đẩy danh sách của country sang bảng Add Brand
            ViewBag.Countries = context.Country.ToList();
            return View();
        }

        //hàm 2: nhận và xử lý dữ liệu được gửi từ form
        [HttpPost]
        public IActionResult Create (Brand brand)
        {
            //check tính hợp lệ của dữ liệu 
            if (ModelState.IsValid)
            {
                //add dữ liệu vào DB
                context.Add(brand);
                context.SaveChanges();
                //hiển thị thông báo thành công về view
                TempData["Message"] = "Add brand successfully !";
                //quay ngược về trang index
                return RedirectToAction(nameof(Index));
            }
            //nếu dữ liệu không hợp lệ thì trả về form để nhập lại
            return View(brand);
        }

        //sửa dữ liệu của bảng
        [HttpGet]
        public IActionResult Edit (int id)
        {
            ViewBag.Countries = context.Country.ToList();
            return View(context.Brand.Find(id));
        }

        [HttpPost]
        public IActionResult Edit (Brand brand)
        {
            //check tính hợp lệ của dữ liệu 
            if (ModelState.IsValid)
            {
                //update dữ liệu vào DB
                context.Update(brand);
                context.SaveChanges();
                //hiển thị thông báo thành công về view
                TempData["Message"] = "Edit brand successfully !";
                //quay ngược về trang index
                return RedirectToAction(nameof(Index));
            }
            //nếu dữ liệu không hợp lệ thì trả về form để nhập lại
            return View(brand);
        }
    }
}

ApplicationDevelopment/demoweb/Controllers/CountryController.cs
using demoweb.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace demoweb.Controllers
{
    public class CountryController : Controller
    {
        //khai báo ApplicationDbContext để truy xuất và thay đổi dữ liệu của bảng
        private ApplicationDbContext context;
        public CountryController (ApplicationDbContext applicationDbContext)
        {
            context = applicationDbContext;
        }

        public IActionResult Detail (int id)
        {
            var country = context.Country.Include(c => c.Brands)      //Country - Brand: 1 - M
                                         .ThenInclude(b => b.Mobiles) //Country => Brand => Mobile
                                         .FirstOrDefault(c => c.Id == id);
            /* Note:
             * Nếu 2 bảng có kết nối trực tiếp (đi thẳng) thì dùng hàm Include
             * Nếu 2 bảng có kết nối gián tiếp (đi vòng) thông qua bảng trung gian thì dùng hàm ThenInclude
             */
            return View(country);
        }
    }
}

ApplicationDevelopment/demoweb/Controllers/MobileController.cs
using demoweb.Data;
using demoweb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace demoweb.Controllers
{
    public class MobileController : Controller
    {
        //khai báo ApplicationDbContext để truy xuất và thay đổi dữ liệu của bảng
        private ApplicationDbContext context;
        public MobileController(ApplicationDbContext applicationDbContext)
        {
            context = applicationDbContext;
        }

        //load toàn bộ dữ liệu của bảng  
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            //xếp mobile mới được hiển thị ở đầu danh sách (sort id giảm dần)
            var mobiles = context.Mobile.OrderByDescending(m => m.Id).ToList();
            return View(mobiles);
        }

        [Authorize(Roles = "Customer")]
        //hiển thị giao diện dạng card cho khách hàng order sản phẩm
        public IActionResult Store()
        {
            return View(context.Mobile.ToList());
        }

        //xoá dữ liệu từ bảng
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            var mobile = context.Mobile.Find(id);
            context.Mobile.Remove(mobile);
            context.SaveChanges();
            TempData["Message"] = "Delete mobile successfully !";
            return RedirectToAction("Index");
        }

        //xem thông tin theo id
        [Authorize(Roles = "Admin, Customer")]
        public IActionResult Detail(int id)
        {
            var mobile = context.Mobile.Include(m => m.Brand)  //Mobile - Brand : M - 1
                                       .ThenInclude(b => b.Country)  //Brand - Country : M - 1
                                       .FirstOrDefault(b => b.Id == id);
            return View(mobile);
        }

        //thêm dữ liệu vào bảng
        //hàm 1: render ra view
        [HttpGet]
        public IActionResult Create()
        {
            //đẩy danh sách của country sang bảng Add Mobile
            ViewBag.Brands = context.Brand.ToList();
            return View();
        }

        //hàm 2: nhận và xử lý dữ liệu được gửi từ form
        [HttpPost]
        public IActionResult Create(Mobile mobile)
        {
            //check tính hợp lệ của dữ liệu 
            if (ModelState.IsValid)
            {
                //add dữ liệu vào DB
                context.Add(mobile);
                context.SaveChanges();
                //hiển thị thông báo thành công về view
                TempData["Message"] = "Add mobile successfully !";
                //quay ngược về trang index
                return RedirectToAction(nameof(Index));
            }
            //nếu dữ liệu không hợp lệ thì trả về form để nhập lại
            return View(mobile);
        }

        //sửa dữ liệu của bảng
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Brands = context.Brand.ToList();
            return View(context.Mobile.Find(id));
        }

        [HttpPost]
        public IActionResult Edit(Mobile mobile)
        {
            //check tính hợp lệ của dữ liệu 
            if (ModelState.IsValid)
            {
                //update dữ liệu vào DB
                context.Update(mobile);
                context.SaveChanges();
                //hiển thị thông báo thành công về view
                TempData["Message"] = "Edit mobile successfully !";
                //quay ngược về trang index
                return RedirectToAction(nameof(Index));
            }
            //nếu dữ liệu không hợp lệ thì trả về form để nhập lại
            return View(mobile);
        }

        public IActionResult PriceAsc()
        {
            var mobiles = context.Mobile.OrderBy(m => m.Price).ToList();
            return View("Store",mobiles);
        }

        public IActionResult PriceDesc()
        {
            var mobiles = context.Mobile.OrderByDescending(m => m.Price).ToList();
            return View("Store",mobiles);
        }

        [HttpPost]
        public IActionResult Search(string keyword)
        {
            var mobiles = context.Mobile.Where(m => m.Name.Contains(keyword)).ToList();
            return View("Store", mobiles);
        }
    }
}

ApplicationDevelopment/demoweb/Views/Brand/Create.cshtml
@model demoweb.Models.Brand

<div class="container col-md-6 text-center mt-3">
    <form class="card p-3 bg-light" asp-controller="Brand" asp-action="Create" method="post">
        <h3 class="text text-primary">Create new mobile brand</h3>
        <div class="form-group">
            <label asp-for="Name" class="text text-success"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text text-danger"></span>
        </div>
          <div class="form-group">
            <label asp-for="CountryId" class="text text-success"></label>
            <select asp-for="CountryId" class="form-control" asp-items="@(new SelectList(ViewBag.Countries,"Id","Name"))">
                <option>Select one</option>
            </select>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Create" />
        </div>
    </form>
</div>

ApplicationDevelopment/demoweb/Views/Brand/Detail.cshtml
@model demoweb.Models.Brand

<div class="container col-md-6 text-center mt-3">
    <table class="table table-bordered">
        <tr>
            <th colspan="2" class="h3 bg-light text-success">@Model.Name</th>
        </tr>
        <tr>
            <th>Country Name</th>
            <td>
                <a class="font-weight-bold text-italic" asp-controller="Country" asp-action="Detail" asp-route-id="@Model.Country.Id">
                    @Model.Country.Name
                </a>
        </tr>
        <tr>
            <th>Mobile List</th>
            <td>
                @foreach (var mobile in Model.Mobiles)
                {
                    <a class="font-weight-bold text-italic" asp-controller="Mobile" asp-action="Detail" asp-route-id="@mobile.Id">
                        @mobile.Name
                    </a>
                    <br />
                }
            </td>
        </tr>
    </table>
</div>

ApplicationDevelopment/demoweb/Views/Brand/Edit.cshtml
@model demoweb.Models.Brand

<div class="container col-md-6 text-center mt-3">
    <form class="card p-3 bg-light" asp-controller="Brand" asp-action="Edit" method="post">
        <input type="hidden" asp-for="Id" />
        <h3 class="text text-primary">Edit mobile brand</h3>
        <div class="form-group">
            <label asp-for="Name" class="text text-success"></label>
            <input asp-for="Name" class="form-control"/>
            <span asp-validation-for="Name" class="text text-danger"></span>
        </div>
          <div class="form-group">
            <label asp-for="CountryId" class="text text-success"></label>
            <select asp-for="CountryId" class="form-control" asp-items="@(new SelectList(ViewBag.Countries,"Id","Name"))">
                <option>Select one</option>
            </select>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Edit" />
        </div>
    </form>
</div>

ApplicationDevelopment/demoweb/Views/Brand/Index.cshtml
@model ICollection<Brand>

<div class="container col-md-6 text-center mt-3">
@if (@TempData["Message"] != null) {
  <p class="alert alert-danger">@TempData["Message"]</p>
}
<table class="table table-bordered">
    <tr>
        <th colspan="2" class="h3 bg-light text-success">Brand List</th>
        <th class="col-md-4">
            <a class="btn btn-primary" asp-controller="Brand" asp-action="Create">
                Add
            </a>
        </th>
    </tr>
    <tr>
        <th>Brand Id</th>
        <th>Brand Name</th>
        <th>Action</th>
    </tr>
    @foreach (var brand in Model)
    {
        <tr>
            <td>@brand.Id</td>
            <td>
                <a class="font-weight-bold" asp-controller="Brand" asp-action="Detail" asp-route-id="@brand.Id">
                    @brand.Name
                </a>
            </td>
            <td>
                <a class="btn btn-warning" asp-controller="Brand" asp-action="Edit" asp-route-id="@brand.Id">
                    Edit
                </a>
                <a class="btn btn-danger" asp-controller="Brand" asp-action="Delete" asp-route-id="@brand.Id"
               onclick="    return confirm('Are you sure to delete this brand ?');">
                    Delete
                </a>
            </td>
        </tr>
    }
</table>
</div>