ApplicationDevelopment/web11/Controllers/CapitalController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using web11.Data;
using web11.Models;

namespace web11.Controllers
{
    public class CapitalController : Controller
    {
        private ApplicationDbContext context;

        public CapitalController(ApplicationDbContext DbContext)
        {
            this.context = DbContext;
        }
        
        public IActionResult Index()
        {
            var capitals = context.Capital
                .Include(c => c.Country)
                .ToList();
            return View(capitals);
        }

        public IActionResult Detail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            //gọi đến capital theo id có chứa liên kết đến bảng Country
            var capital = context.Capital
                    .Include(c => c.Country)
                    .FirstOrDefault(c => c.Id == id);
            return View(capital);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            //tạo object capital chứa id cần xóa
            var capital = context.Capital.Find(id);
            //dùng DbContext để xóa objet
            context.Remove(capital);
            //lưu lại thay đổi trong DB
            context.SaveChanges();
            //gửi thông báo về view thông qua TempData
            TempData["Info"] = "Delete capital succeed !";
            //quay ngược về action Index sau khi thành công
            return RedirectToAction("Index");
        }

        //hàm này để render ra form Add cho người dùng nhập
        [HttpGet]
        public IActionResult Add ()
        {
            //sử dụng ViewBag để đẩy dữ liệu của bảng Country vào form
            var countries = context.Country.ToList();
            ViewBag.Countries = countries;
            return View();
        }

        //hàm này để nhận và xử lý dữ liệu từ form
        [HttpPost] 
        public IActionResult Add (Capital capital)
        {
            //validate dữ liệu từ form thông qua annotation của Model
            if (ModelState.IsValid)
            {
                //add dữ liệu vào DB nếu hợp lệ
                context.Add(capital);
                context.SaveChanges();
                //trả thông báo về view
                TempData["Info"] = "Add capital succeed !";
                //redirect về trang index
                return RedirectToAction(nameof(Index));
            }
            //nếu dữ liệu nhập vào không hợp lệ trả lại form cùng với dữ liệu đã nhập
            return View(capital);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            //check id null
            if (id == null)
            {
                return NotFound();
            }
            //đẩy dữ liệu của bảng Country vào form
            var countries = context.Country.ToList();
            ViewBag.Countries = countries;
            //tạo object capital lấy từ DB theo id
            var capital = context.Capital.Find(id);
            //render ra form Edit cùng với dữ liệu sẵn có
            return View(capital);
        }

        [HttpPost]
        public IActionResult Edit(Capital capital)
        {
            if (ModelState.IsValid)
            {
                //update dữ liệu vào DB nếu hợp lệ
                context.Update(capital);
                context.SaveChanges();
                //trả thông báo về view
                TempData["Info"] = "Edit capital succeed !";
                //redirect về trang index
                return RedirectToAction(nameof(Index));
            }
            //nếu dữ liệu nhập vào không hợp lệ trả lại form cùng với dữ liệu đã nhập
            return View(capital);
        }
    }
}

ApplicationDevelopment/web11/Controllers/CountryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using web11.Data;

namespace web11.Controllers
{
    public class CountryController : Controller
    {
        private ApplicationDbContext context;

        public CountryController(ApplicationDbContext DbContext)
        {
            this.context = DbContext;
        }
        
        public IActionResult Index()
        {
            return View(context.Country
                            .Include(c => c.Capital)
                            .ToList());
        }
    }
}

ApplicationDevelopment/web11/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - web11</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">web11</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Country</a>
                        </li>
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Capital" asp-action="Index">Capital</a>
                        </li>
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bank" asp-action="Index">Bank</a>
                        </li>
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Branch" asp-action="Index">Branch</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Course</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - web11 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>