ApplicationDevelopment/demoweb/Controllers/BrandController.cs
using demoweb.Data;
using demoweb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace demoweb.Controllers
{
    public class BrandController : Controller
    {
        //khai báo ApplicationDbContext để truy xuất và thay đổi dữ liệu của bảng
        private ApplicationDbContext context;
        public BrandController (ApplicationDbContext applicationDbContext)
        {
            context = applicationDbContext;
        }

        //load toàn bộ dữ liệu của bảng  
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(context.Brand.ToList());
        }

        //xoá dữ liệu từ bảng
        
        public IActionResult Delete(int id)
        {
            var brand = context.Brand.Find(id);
            context.Brand.Remove(brand);
            context.SaveChanges();
            TempData["Message"] = "Delete brand successfully !";
            return RedirectToAction("Index");
        }

        //xem thông tin theo id
        public IActionResult Detail (int id)
        {
            var brand = context.Brand.Include(b => b.Mobiles)  //Brand - Mobile : 1 - M
                                     .Include(b => b.Country)  //Brand - Country : M - 1
                                     .FirstOrDefault(b => b.Id == id);
            return View(brand);
        }

        //thêm dữ liệu vào bảng
        //hàm 1: render ra view
        [HttpGet]
        public IActionResult Create()
        {
            //đẩy danh sách của country sang bảng Add Brand
            ViewBag.Countries = context.Country.ToList();
            return View();
        }

        //hàm 2: nhận và xử lý dữ liệu được gửi từ form
        [HttpPost]
        public IActionResult Create (Brand brand)
        {
            //check tính hợp lệ của dữ liệu 
            if (ModelState.IsValid)
            {
                //add dữ liệu vào DB
                context.Add(brand);
                context.SaveChanges();
                //hiển thị thông báo thành công về view
                TempData["Message"] = "Add brand successfully !";
                //quay ngược về trang index
                return RedirectToAction(nameof(Index));
            }
            //nếu dữ liệu không hợp lệ thì trả về form để nhập lại
            return View(brand);
        }

        //sửa dữ liệu của bảng
        [HttpGet]
        public IActionResult Edit (int id)
        {
            ViewBag.Countries = context.Country.ToList();
            return View(context.Brand.Find(id));
        }

        [HttpPost]
        public IActionResult Edit (Brand brand)
        {
            //check tính hợp lệ của dữ liệu 
            if (ModelState.IsValid)
            {
                //update dữ liệu vào DB
                context.Update(brand);
                context.SaveChanges();
                //hiển thị thông báo thành công về view
                TempData["Message"] = "Edit brand successfully !";
                //quay ngược về trang index
                return RedirectToAction(nameof(Index));
            }
            //nếu dữ liệu không hợp lệ thì trả về form để nhập lại
            return View(brand);
        }
    }
}

ApplicationDevelopment/demoweb/Controllers/OrderController.cs
using demoweb.Data;
using demoweb.Models;
using Microsoft.AspNetCore.Mvc;
using System;

namespace demoweb.Controllers
{
    public class OrderController : Controller
    {
        //khai báo ApplicationDbContext để truy xuất và thay đổi dữ liệu của bảng
        private ApplicationDbContext context;
        public OrderController(ApplicationDbContext applicationDbContext)
        {
            context = applicationDbContext;
        }

        [HttpPost]
        public IActionResult Make(int id, int quantity)
        {
            //tạo Order mới
            var order = new Order();
            //set giá trị trong từng thuộc tính của Order
            var mobile = context.Mobile.Find(id);
            order.Mobile = mobile;
            order.MobileId = id;
            order.OrderQuantity = quantity;
            order.OrderPrice = mobile.Price * quantity;
            order.OrderDate = DateTime.Now;
            order.UserEmail = User.Identity.Name;
            //add Order vào DB
            context.Order.Add(order);
            //trừ quantity của mobile
            mobile.Quantity -= quantity;
            context.Mobile.Update(mobile);
            //lưu cập nhật vào DB
            context.SaveChanges();
            //gửi về thông báo order thành công
            TempData["Success"] = "Order mobile successfully !";
            //redirect về trang mobile store
            return RedirectToAction("Store", "Mobile");
        }
    }
}

ApplicationDevelopment/demoweb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Online Book Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @*  set navigation bar cho role admin*@
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="h3 text text-success ml-3" asp-area="" asp-controller="Mobile" asp-action="Index">Mobile</a>
                            </li>
                            <li class="nav-item">
                                <a class="h3 text text-success ml-3" asp-area="" asp-controller="Brand" asp-action="Index">Brand</a>
                            </li>
                            <li class="nav-item">
                                <a class="h3 text text-success ml-3" asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                            </li>
                        </ul>
                    }
                    else if (User.Identity.IsAuthenticated && User.IsInRole("Customer"))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="h3 text text-primary" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="h3 text text-success ml-3" asp-area="" asp-controller="Mobile" asp-action="Store">Store</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            <span class="alert alert-primary">Online Book Store - Demo Web Project - 1670 - Summer 2022</span>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>